### ISSUE TITLE
Working in Linux containers?

### ISSUE THREAD

**Issue by christophwille** [Azure/azuremonitor-opentelemetry-profiler-net#12]
I didn't see an explicit mention. 

My question stems from the Snapshot debugger that was/is Windows-only as per https://learn.microsoft.com/en-us/azure/azure-monitor/snapshot-debugger/snapshot-debugger#applications and I just want to make sure that Linux containers are a-ok to use with it.

**Comment by xiaomi7732** [comment]
@christophwille Thanks for the ask. Early access / beta stage aside, this profiler is designed to work with Linux containers as well as windows.

We will update the document to clarify it.

**Comment by xiaomi7732** [comment]
Readme has been updated. Close this one. Thanks for the feedback.
